<?php
require_once __DIR__ . '/BaseController.php';
require_once __DIR__ . '/../models/Listing.php';
require_once __DIR__ . '/../models/SellerModel.php';
require_once __DIR__ . '/../models/Review.php';
class SellerController extends BaseController {
    public function dashboard(){ require_role(['seller','buyer']); $listing=new Listing($this->conn); $seller=new SellerModel($this->conn); $listings=current_role()==='seller'?$listing->bySeller(current_user_id()):[]; $request=$seller->requestByUser(current_user_id()); $this->view('seller/dashboard',compact('listings','request')); }
    public function verification(){ require_login(); $seller=new SellerModel($this->conn); $request=$seller->requestByUser(current_user_id()); $message=''; if($_SERVER['REQUEST_METHOD']==='POST'){ $doc=upload_file('id_document','documents',['jpg','jpeg','png','pdf']); if(!$doc||trim($_POST['motivation'])==='') $message='Motivation and valid ID document are required.'; else { $seller->requestVerification(current_user_id(),trim($_POST['motivation']),$doc); $message='Verification request submitted.'; $request=$seller->requestByUser(current_user_id()); }} $this->view('seller/verification',compact('request','message')); }
    public function createListing(){ require_seller_verified(); $m=new Listing($this->conn); $cats=$m->categories(); $message=''; if($_SERVER['REQUEST_METHOD']==='POST'){ $errors=$this->listingErrors($_POST); if(!$errors){ $id=$m->create(current_user_id(),(int)$_POST['category_id'],trim($_POST['title']),trim($_POST['description']),$_POST['item_condition'],(float)$_POST['starting_price'],($_POST['reserve_price']===''?null:(float)$_POST['reserve_price']),$_POST['end_datetime']); for($i=0;$i<5;$i++){ if(!empty($_FILES['images']['name'][$i])){ $_FILES['single_image']=['name'=>$_FILES['images']['name'][$i],'type'=>$_FILES['images']['type'][$i],'tmp_name'=>$_FILES['images']['tmp_name'][$i],'error'=>$_FILES['images']['error'][$i],'size'=>$_FILES['images']['size'][$i]]; $path=upload_file('single_image','listings',['jpg','jpeg','png','gif']); if($path) $m->addImage($id,$path,$i+1); }} $message='Listing submitted for moderator review.'; } else $message=$this->errors($errors); } $this->view('seller/create_listing',compact('cats','message')); }
    private function listingErrors($p){ $e=[]; if(trim($p['title']??'')==='')$e[]='Title required'; if(trim($p['description']??'')==='')$e[]='Description required'; if((float)($p['starting_price']??0)<=0)$e[]='Starting price must be positive'; if(!empty($p['reserve_price'])&&(float)$p['reserve_price']<(float)$p['starting_price'])$e[]='Reserve cannot be lower than starting price'; if(strtotime($p['end_datetime']??'')<time()+3600)$e[]='End date must be at least 1 hour in future'; return $e; }
    public function listings(){ require_seller_verified(); $rows=(new Listing($this->conn))->bySeller(current_user_id()); $this->view('seller/listings',compact('rows')); }
    public function editListing(){ require_seller_verified(); $m=new Listing($this->conn); $listing=$m->find((int)$_GET['id']); $cats=$m->categories(); $message=''; if($_SERVER['REQUEST_METHOD']==='POST'){ $m->updateIfNoBids((int)$_GET['id'],current_user_id(),trim($_POST['title']),trim($_POST['description']),$_POST['item_condition'],(float)$_POST['starting_price'],($_POST['reserve_price']===''?null:(float)$_POST['reserve_price']),$_POST['end_datetime']); $message='Listing updated if it had zero bids.'; $listing=$m->find((int)$_GET['id']); } $this->view('seller/edit_listing',compact('listing','cats','message')); }
    public function templates(){ require_seller_verified(); $s=new SellerModel($this->conn); $m=new Listing($this->conn); $cats=$m->categories(); if($_SERVER['REQUEST_METHOD']==='POST') $s->createTemplate(current_user_id(),trim($_POST['title']),trim($_POST['description']),(int)$_POST['category_id'],$_POST['item_condition'],(float)$_POST['starting_price']); $rows=$s->templates(current_user_id()); $this->view('seller/templates',compact('rows','cats')); }
    public function ended(){ require_seller_verified(); $rows=(new SellerModel($this->conn))->ended(current_user_id()); $this->view('seller/ended',compact('rows')); }
    public function analytics(){ require_seller_verified(); $stats=(new SellerModel($this->conn))->analytics(current_user_id()); $this->view('seller/analytics',compact('stats')); }
    public function reviews(){ require_seller_verified(); $review=new Review($this->conn); if($_SERVER['REQUEST_METHOD']==='POST') $review->respond((int)$_POST['review_id'],current_user_id(),trim($_POST['response_text'])); $rows=$review->received(current_user_id()); $this->view('seller/reviews',compact('rows')); }
    public function relist(){ require_seller_verified(); redirect_to('index.php?page=create_listing'); }
}
?>
